name: "cfm"

model:
  track_history: False
  num_voxels: 6480
  input_vars: &INPUT_VARS
    z_vars: ["e"]
    c_vars: ["e_inc"]

  transforms: &TRANSFORMS 
    e: "sqrt"
  num_steps: 40

  encoder: null
  mlp:
    hidden_layers: [128, 128]
    activation: "relu"
    layer_norm: False

trainer:
  epochs: 5
  patience: 1

optimizer: 
  type: adam
  lr: 0.00001

logger:
  log_dir: "logs/sweep/cfm"

data_loader:
  load_dir: "data/test5"
  num_files: 1
  standardize_vars: ["e_log_norm", "e_sqrt_norm", "e_inc_norm"]
  transforms: *TRANSFORMS
  input_vars: *INPUT_VARS
  batch_size: 128
  data_view: "event"
  is_ragged: True
  batch_mode: 
    name: "sparse"
